import type { Metadata } from "next";
import { Aladin, Merriweather } from "next/font/google";
import "./globals.css";
import Footer from "@/Components/Footer";

const geistSans = Aladin({
  variable: "--Prime",
  subsets: ["latin"],
  weight: "400",
});

const geistMono = Merriweather({
  variable: "--Secound",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Coffee Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
